const int buzzer = 9; //buzzer to arduino pin 9

void setup(){
 
  pinMode(buzzer, OUTPUT); // Set buzzer - pin 9 as an output

}

void loop(){
  
  tone(buzzer, 146.8324); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(50);        // ...for 1sec
  
  tone(buzzer, 146.8324); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(150);        // ...for 1sec
  
  tone(buzzer, 293.6648); // Send 1KHz sound signal...
  delay(200);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(150);        // ...for 1sec
  
  tone(buzzer, 246.9417); // Send 1KHz sound signal...
  delay(150);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(350);        // ...for 1sec
  
    tone(buzzer, 220.0000); // Send 1KHz sound signal...
  delay(150);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(150);        // ...for 1sec
  
      tone(buzzer, 207.6523); // Send 1KHz sound signal...
  delay(150);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(150);        // ...for 1sec
  
        tone(buzzer, 184.9972); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(125);        // ...for 1sec
  
  tone(buzzer, 164.8138); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(125);        // ...for 1sec
  
  tone(buzzer, 184.9972); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);        // ...for 1sec
  
  tone(buzzer, 207.6523); // Send 1KHz sound signal...
  delay(250);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);        // ...for 1sec
}
